create table public.gift_certificates
(
    id               integer generated by default as identity
        primary key,
    name             varchar(32),
    description      varchar(128),
    price            real,
    duration         bigint,
    create_date      timestamp,
    last_update_date timestamp,
    constraint gift_certificates_pk2
        unique (name, description)
);


create table if not exists public.tags
(
    id   integer generated by default as identity
        primary key,
    name varchar(32)
);

create table if not exists public.certificate_tag
(
    certificate_id integer,
    tag_id         integer,
    constraint certificate_tag_pk
        primary key (certificate_id, tag_id)
);



