create table if not exists public.gift_certificates
(
    id               integer generated by default as identity
        primary key,
    name             varchar(32),
    description      varchar(128),
    price            real,
    duration         bigint,
    create_date      timestamp,
    last_update_date timestamp,
    constraint gift_certificates_pk2
        unique (name, description)
);


create table if not exists public.tags
(
    id   integer generated by default as identity
        primary key,
    name varchar(32)
);

create table public.certificate_tag
(
    tag_id         integer not null
        constraint tag_id_fk
            references public.tags,
    certificate_id integer not null
        constraint cert_id_pk
            references public.gift_certificates
);

create table public.users
(
    id       serial
        primary key,
    username varchar(255)
);

create table public.users_gift_certificates
(
    user_id            integer not null
        constraint user_id_fk
            references public.users,
    certificate_id integer not null
        constraint certificate_id_fk
            references public.gift_certificates
);